site_name: Samarium Documentation 
copyright: Copyright &copy; 2022 Samarium
repo_url: https://github.com/samarium-lang/Samarium
repo_name: samarium-lang/Samarium
nav:
  - Home: index.md
  - Base Samarium:
    - Variables: variables.md
    - Integers: integers.md
    - Operators: operators.md
    - Strings: strings.md
    - Comments: comments.md
    - Arrays: arrays.md
    - Slices: slices.md
    - Tables: tables.md
    - Built-in Functions: builtins.md
    - Control Flow: controlflow.md
    - Functions: functions.md
    - Modules: modules.md
    - Classes: classes.md
    - File I/O: fileio.md
  - Standard Library:
    - "collections module": stdcollections.md
    - "iter module": stditer.md
    - "math module": stdmath.md
    - "operator module": stdoperator.md
    - "random module": stdrandom.md
    - "string module": stdstring.md
    - "types module": stdtypes.md
  - Tools: tools.md
theme:
  name: material
  logo: assets/icon-white.png
  favicon: assets/icon-black.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra_javascript:
  - https://unpkg.com/shiki
  - assets/script.js
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - footnotes
